#!/bin/bash

#Part (a)
#Ask user to enter the file name
while true; do
    echo -e "\nEnter a filename:"
    read Filename
    #Check if able to find the file
    if [[ -f "$Filename" ]]; then
        break
    else
        echo "The filename does not exist"
    fi
done

#Part (b)
while IFS=':' read -r username _ uid _ _ _ shell ; do
    #Check if the file format is correct
    if [[ -z "$shell" ]]; then
    echo "Wrong file"
    #Exit the script
        exit 1
    fi
    #Check if uid is number
    if ! [[ "$uid" =~ ^[0-9]+$ ]]; then
        echo "Wrong file format"
        #Exit the script
        exit 1
    fi
done < "$Filename"

#Count users with shell and find largest UID
num_user=0
large_id=0

while IFS=':' read -r username _ uid _ _ _ shell; do
    if [[ "$shell" == "/bin/bash" || "$shell" == "/bin/sh" ]]; then
        echo -e "\n$username"
        ((num_user++))
    fi

    if [[ "$uid" =~ ^[0-9]+$ ]] && (( uid > large_id )); then
        large_id="$uid"
    fi
done < "$Filename"

#Print the statement
echo -e "\nNumber of user account is $num_user"
echo -e "\nThe largest user id (UID) among all the user accounts is $large_id"

#Flip the condition for Part(a) 4 first bullet point
if [[ $(stat -c "%A" "$Filename" | cut -c8) != "r" ]]; then
    chmod 764 "$Filename"
    echo -e "\nYour permission has been flip"
else
#Change the owner and user to userSUSS
    sudo chown userSUSS:userSUSS "$Filename"
    echo -e "\nOwner and group changed to userSUSS"
fi
